### PR TITLE
entire dapp rewrite

### PR DESCRIPTION
**Pull request by maVexxe**
entire dapp rewrite
main changes:
operations such as approval, mint, connect wallet happen in one button
supports more wallets (added coinbase and injected)
added faq
added footer
new design

tested:
all available operations on browser and mobile with different wallet states and different connection states, amounts with or without decimals, only decimals too
tests were performed manually

fixes:
#94
#48

installation:
yarn next build
add environment variables
NEXT_PUBLIC_INFURA_ID
or
NEXT_PUBLIC_ALCHEMY_ID
or both

misc: #6 and #1 can be closed 

https://staking-steel.vercel.app/

### CODE REVIEW

**Comment by sambacha** [comment]
#### 📝 Changed routes:


| [**/**](https://manifold-staking-dapp-4k457ly8m-manifold.vercel.app/) |
|:-:|
|<a href="https://manifold-staking-dapp-4k457ly8m-manifold.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ApCgbSO5cxC7pgAEJQtoMx30U7-brQ74QuREd0h5SQYcHZkStPc6Uaxknb1KsVUrQB1TZwOCTFJrC3o9bD-DqA.png">(view full size)</a> |





5 deleted routes:
- **/404**
- **/faqs**
- **/mint**
- **/stake**
- **/vote**

Commit 36816ab1d69b613b12f58aad0c1092d874ba7c47 (https://manifold-staking-dapp-4k457ly8m-manifold.vercel.app).

**Comment by sambacha** [comment]
Will look at the PR tonight/tomorrow , i have enabled vercel builds

**Comment by sambacha** [comment]
We would like to retain the styling we have now, don't make any changes to the coloring, etc.

**Comment by maVexxe** [comment]
ok i will retain design of the current app

**Comment by sambacha** [comment]
Did you ever email me?

**Comment by maVexxe** [comment]
we wrote in dms on telegram my handle is @ mavexxe. sorry i dont have bandwidth for remaking this currently

**Pull request closed without merging**
