### PR TITLE
feat: added ens avatar support

### PR DESCRIPTION
**Pull request by sasicodes**
Added ENS avatar support if the user has one, else fallbacks to jazzicon.

image

### CODE REVIEW

**Comment by sasicodes** [comment]
@sambacha can you verify this? 🙇🏻

**Comment by sambacha** [comment]
> @sambacha can you verify this? 🙇🏻

sry4thewait

**Review by sambacha — APPROVED** [review]

**Comment by sambacha** [comment]
> @sambacha can you verify this? 🙇🏻

We will be releasing a new design framework if you are interested in any bounties or grants be sure to check it out

**Comment by sasicodes** [comment]
@sambacha love to know more about it

**Pull request merged**
